name: Update Directories and Files JSON

on:
  push:
    branches:
      - main  # Change if your default branch is different
  workflow_dispatch:

permissions:
  contents: write  # Allows GitHub Actions to push changes

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate directories.json
        run: |
          echo '{ "directories": {' > directories.json
          
          # Scan only inside /results/ directory
          find results -type d | while read -r dir; do
            dirname=$(echo "$dir" | sed 's|^\./||')  # Remove leading "./"
            echo "    \"$dirname\": {" >> directories.json
            
            # List files in the directory
            echo '      "files": [' >> directories.json
            files=$(find "$dir" -maxdepth 1 -type f | sed 's|^\./||' | jq -R -s -c 'split("\n")[:-1]')
            if [ -z "$files" ]; then
              echo '      []' >> directories.json
            else
              echo "      $files" >> directories.json
            fi
            echo '      ],' >> directories.json
            
            # List subdirectories
            echo '      "subdirectories": [' >> directories.json
            subdirs=$(find "$dir" -mindepth 1 -maxdepth 1 -type d | sed 's|^\./||' | jq -R -s -c 'split("\n")[:-1]')
            if [ -z "$subdirs" ]; then
              echo '      []' >> directories.json
            else
              echo "      $subdirs" >> directories.json
            fi
            echo '      ]' >> directories.json

            echo "    }," >> directories.json
          done

          # Remove last comma from JSON (fix JSON structure)
          sed -i '$ s/,$//' directories.json

          echo '  }' >> directories.json
          echo '}' >> directories.json

      - name: Commit and Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
          git fetch origin
          git checkout main
          git add directories.json
          git commit -m "Auto-update directories.json with recursive structure [skip ci]" || exit 0
          git push origin main