name: Update Directories and Files JSON

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate directories.json
        run: |
          echo '{ "directories": {"results": {' > directories.json

          find results -mindepth 1 -type d | while read -r dir; do
            dirname=$(basename "$dir")
            fullpath=$(echo "$dir" | sed 's|^\./||')

            # Extract language, section (blog/resources/events), and slug using awk
            lang_part=$(echo "$dirname" | awk -F'--' '{print $1}')
            section_part=$(echo "$dirname" | awk -F'--' '{print $2}')
            slug_part=$(echo "$dirname" | awk -F'--' '{print $3}')

            # If section_part is missing, treat it as a default blog
            if [[ -z "$slug_part" ]]; then
              slug_part="$section_part"
              section_part="blog" # Default to blog if not provided
            fi

            # Construct the full URL dynamically
            if [[ "$lang_part" == "blog" || "$lang_part" == "resources" || "$lang_part" == "events" ]]; then
              base_url="https://toaglobal.com"
              final_url="$base_url/$lang_part/$slug_part/"
            else
              base_url="https://toaglobal.com/$lang_part"
              final_url="$base_url/$section_part/$slug_part/"
            fi

            echo "    \"$dirname\": {" >> directories.json
            echo "      \"url\": \"$final_url\"," >> directories.json

            files=$(find "$dir" -maxdepth 1 -type f -name "*.html" | sed 's|^\./||' | jq -R -s -c 'split("\n")[:-1]')
            echo "      \"files\": $files," >> directories.json

            echo "      \"subdirectories\": []" >> directories.json
            echo "    }," >> directories.json
          done

          sed -i '$ s/,$//' directories.json
          echo '  }}}' >> directories.json

      - name: Commit and Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
          git fetch origin
          git checkout main
          git add directories.json
          git commit -m "Fix dynamic URL structure for blog/resources/events [skip ci]" || exit 0
          git push origin main